### ISSUE TITLE
Logging strategy

### ISSUE THREAD

**Issue by boennemann** [eHealthAfrica/kazana#24] opened 2015-08-26 12:11 UTC
As raised by @gr2m the logging for kazana apps is currently a very simple, bare `console.log` based thing. It would make sense to implement a more sophisticated logging, so one can easily set different loglevels, which helps **a lot** for both people writing the log messages and consumers being able to report very detailed an helpful logs for raising issues.

The module I ended up using a lot for this recently is `npmlog`, which is the logger used for the `npm` CLI. https://github.com/npm/npmlog
It has a very decent default configuration, several reasonable loglevels, it writes all logs to stderr by default, and you can style everything however you like and set a prefix, so messages can be clearly assigned to kazana by users.

The different levels are: silly, verbose, info, http, warn, error (and silent).

I think http, warn and error are clear enough. What I've found a good approach is to use "info" for things that worked as they should've, verbose for logging configuration and internals and silly for pretty much everything you're doing. Most code comments can mostly be replaced with a silly log. This way you can keep the docs, but you can also see exactly see where to program is and where it (potentially) failed.

You can also combine hapi, good and npmlog so the hapi debug output is written with npmlog. See how we've done it for hoodie: https://github.com/hoodiehq/hoodie-server/blob/next/lib/hapi/logger.js

**Comment by jo** [comment] 2015-09-01 09:55
Just want to note that we're using Sentry and I [recently implemented minimalistic logging for a migration service](https://github.com/eHealthAfrica/migration-followup-separate-followups/blob/master/lib/logger.js).

npmlog looks great. Has anybody used it with Sentry?

**Comment by gr2m** [comment] 2015-09-04 05:19
I've added npm logging as we do it in hoodie via 386fa06

**Comment by jo** [comment] 2015-09-07 12:32
I'm not sure if I like it. I currently see an error but there is no hint where it comes from:

```sh
[jo@localhost van]$ npm start

> van@1.2.0 start ~van
> kazana

backend.location not set, starting PouchDB Server at 4999 ...
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at EventEmitter.emit (events.js:87:13)
    at EventEmitter.<anonymous> (~kazana-server/node_modules/npmlog/log.js:159:22)
    at EventEmitter.<anonymous> (~kazana-server/node_modules/npmlog/log.js:230:21)
    at logger (~kazana-server/lib/plugins/logger.js:46:9)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at internals.Squeeze._transform (~kazana-server/node_modules/good-squeeze/lib/squeeze.js:31:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)

npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! van@1.2.0 start: `kazana`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the van@1.2.0 start script 'kazana'.
npm ERR! This is most likely a problem with the van package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     kazana
npm ERR! You can get their info via:
npm ERR!     npm owner ls van
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~van/npm-debug.log
```

**Comment by gr2m** [comment] 2015-09-07 18:23
@jo I can't reproduce the  issue. Do I need some data in my db to reproduce it?

**Comment by patriciagarcia** [comment] 2015-10-28 18:05
@gr2m, @jo, can we close this? is there an issue?

**Comment by gr2m** [comment] 2015-11-03 19:38
This is resolved by https://github.com/eHealthAfrica/kazana-server/pull/59

**Closed by gr2m** 2015-11-03 19:38 UTC
Labels: ready
