### ISSUE TITLE
after server started, look for deleted data reports, and delete their indicators

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana#112] opened 2015-11-05 02:04 UTC
follow up for https://github.com/eHealthAfrica/kazana/issues/79#issuecomment-153928604

**Comment by patriciagarcia** [comment] 2015-11-09 14:44
Duplicate of https://github.com/eHealthAfrica/kazana-server/issues/76

**Closed by patriciagarcia** 2015-11-09 14:44 UTC
Labels: bug, ready
